### ISSUE TITLE
Implement Initial IAM

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/DigitalPy#53]
The IAM component in DigitalPy is designed to support standard authentication and authorization protocols, catering to both internal and external applications, API developers, and end-users. It ensures secure access control and identity management within the framework.

To move forward with the development of this component we need to realize the fundamental use case of Access Control.

Access Control Determines user permissions and access levels, ensuring users are only able to perform actions they are authorized for.

Role-Based Access Control (RBAC): Implements RBAC to manage user roles and permissions, enabling fine-grained access control.

```[tasklist]
### Tasks
- [x] Implement SQLAlchemy based IAM persistency
- [x] Add Strategy Pattern for dynamic filtering
- [ ] Include Numba for optimization
- [ ] Create IAM Service
- [ ] Cache database read operations
- [ ] Implement IAM Session Table
```
