### ISSUE TITLE
Implement Service Management Component

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/DigitalPy#84]
```[tasklist]
### Tasks
- [x] Migrate service management to thread in core
- [x] Migrate subject to execute within core
- [x] Implement communication between subject and core threads
- [x] Add status enumeration
- [x] Start TCP Service
- [x] Stop TCP Service
- [x] Get Service Status
- [x] Add Digitalpy Service Docs
- [ ] Update Enumeration Contents
```

Demo contents:
1. Start a TCP Service
2. Connect with client and demo basic functionality
3. Get Service Status
4. Stop TCP Service
5. Show connection fails
6. Review Digitalpy Docs for quality
